### ISSUE TITLE
Pypi release

### ISSUE THREAD

**Issue by darosior** [kirbyfan64/mrkd#3]
Hello @refi64,

we use `mrkd` for another [open source project](https://github.com/ElementsProject/lightning), and that's that use in real conditions that made us pushed some patches. Can I ask you to make a new Pypi release for that pretty useful piece of Python, so that we can use the latest modifications in a [cleaner way](https://github.com/ElementsProject/lightning/pull/3113/commits/4957202146f4456900d9b3de7695a3b1be966132) :-) ?

**Comment by refi64** [comment]
Will do tomorrow! I trying to get it today, but I realized I forgot to
configure my pypirc so it got delayed a bit. ¯\_(ツ)_/¯

**Comment by darosior** [comment]
Great, thank you !

**Comment by refi64** [comment]
Just pushed it! BTW I will admit it's interesting to use mrkd used elsewhere, I thought I would always be pretty much the only user.

**Comment by darosior** [comment]
> Just pushed it!

Thanks

> BTW I will admit it's interesting to use mrkd used elsewhere, I thought I would always be pretty much the only user.

Yeah, actually we needed Markdown for a [readthedocs](https://lightning.readthedocs.io/) and we were using asciidoc for manpages. Maintaining both .md and .txt was not an option, and I found your package : it does the job, that's all we need :-).
